apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
spec:
  selector:
    app: kafka-producer # Выбор подов, принадлежащих вашему приложению producer
  ports:
    - protocol: TCP
      port: 8088 # Порт, на котором работает ваше приложение producer в контейнере
      targetPort: 8088 # Порт вашего приложения producer в контейнере
